# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# GPS_Pts_to_CSV_File.py
# Created on: 2015-02-01 11:53:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: GPS_Pts_to_CSV_File <Expression> <Tej_1_3_csv> 
# Description: Python script for exporting a gully crosssection to a .csv file
# ---------------------------------------------------------------------------

########### Make sure to download the DEM of the Tejeria region (northern Spain).
########### The file can be downloaded from the following link:
########### https://sendit.wur.nl/Download.aspx?id=794ff435-2bdb-43c7-8eb1-2061e6a44c1c
########### "Place the DEM in the following directory: "D:\\GullyGeoChallenge\\data"

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("D:/GullyGeoChallenge/Scripting/Python/CreatePointsFromLinesTool/CreatePointsFromLines.pyt")

# Overwrite pre-existing files
arcpy.env.overwriteOutput = True

# Set Geoprocessing environments
arcpy.env.newPrecision = "DOUBLE"
arcpy.env.autoCommit = "1000"
arcpy.env.XYResolution = "0.001 Meters"
arcpy.env.XYDomain = ""
arcpy.env.scratchWorkspace = "D:/GullyGeoChallenge/data/Step.gdb"
arcpy.env.cartographicPartitions = ""
arcpy.env.terrainMemoryUsage = "true"
arcpy.env.MTolerance = ""
arcpy.env.compression = "LZ77"
arcpy.env.coincidentPoints = "MEAN"
arcpy.env.randomGenerator = "0 ACM599"
arcpy.env.outputCoordinateSystem = ""
arcpy.env.rasterStatistics = "STATISTICS 1 1"
arcpy.env.ZDomain = ""
arcpy.env.transferDomains = "false"
arcpy.env.resamplingMethod = "NEAREST"
arcpy.env.snapRaster = ""
arcpy.env.projectCompare = "NONE"
arcpy.env.cartographicCoordinateSystem = ""
arcpy.env.configKeyword = ""
arcpy.env.outputZFlag = "Disabled"
arcpy.env.qualifiedFieldNames = "true"
arcpy.env.tileSize = "128 128"
arcpy.env.parallelProcessingFactor = ""
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
arcpy.env.referenceScale = ""
arcpy.env.extent = "DEFAULT"
arcpy.env.XYTolerance = "0.001 Meters"
arcpy.env.tinSaveVersion = "CURRENT"
arcpy.env.nodata = "NONE"
arcpy.env.MDomain = ""
arcpy.env.spatialGrid1 = "0"
arcpy.env.cellSize = "MAXOF"
arcpy.env.outputZValue = ""
arcpy.env.outputMFlag = "Same As Input"
arcpy.env.geographicTransformations = ""
arcpy.env.spatialGrid2 = "0"
arcpy.env.ZResolution = ""
arcpy.env.mask = ""
arcpy.env.spatialGrid3 = "0"
arcpy.env.maintainSpatialIndex = "false"
arcpy.env.workspace = "D:/GullyGeoChallenge/data/Step.gdb"
arcpy.env.MResolution = ""
arcpy.env.derivedPrecision = "DOUBLE"
arcpy.env.ZTolerance = ""

# Directories of DEM and GPS Points
tejeria_dsm_medium_tif = "D:/GullyGeoChallenge/data/tejeria_dsm_medium.tif"
GPS_Points_Tejeria_shp = "D:/GullyGeoChallenge/data/GPS_points/GPS_Points_Tejeria.shp"

# Process: Select
# Set GPS points in the expression below.
# Replace one of the following combinations for the 001 and 003 in the expression.
# Valid combinations are: (001, 003); (0013, 0016); (0026, 0028); (039, 041); (048, 050);
# (073, 075); (078, 079); (0115, 0117); (0146, 0147); (0148, 0149)

Expression = "\"id\" = 'TEJGUL0026' OR \"id\" = 'TEJGUL0028'"
Selected_Points = "D:/GullyGeoChallenge/data/Step.gdb/Selected_Points"
arcpy.Select_analysis(GPS_Points_Tejeria_shp, Selected_Points, Expression)

# Process: Points To Line
Points_to_Line = "D:/GullyGeoChallenge/data/Step.gdb/Points_to_Line"
arcpy.PointsToLine_management(Selected_Points, Points_to_Line, "", "y", "NO_CLOSE")

# Process: Create Points Along Lines
Points_along_Line = "D:/GullyGeoChallenge/data/Step.gdb/Points_along_Line"
arcpy.CreatePointsAlongLines_alonglines(Points_to_Line, Points_along_Line, "0.05", "VALUE", "NO_END_POINTS")

# Process: Extract Values to Points
Values_Extracted_to_Points = "D:/GullyGeoChallenge/data/Step.gdb/Values_Extracted_to_Points"
arcpy.gp.ExtractValuesToPoints_sa(Points_along_Line, tejeria_dsm_medium_tif, Values_Extracted_to_Points, "NONE", "VALUE_ONLY")

# Process: Add Field
arcpy.AddField_management(Values_Extracted_to_Points, "Distance", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
Expression_2 = "([OBJECTID] -1) * 0.05"
arcpy.CalculateField_management(Values_Extracted_to_Points, "Distance", Expression_2, "VB", "")

# Process: Export Feature Attribute to ASCII
# Change the GPS number sin the Tej_csv parameter (1 and 3 set as standard) to the points chosen in the select tool above).
# Leave the 0s in front of the numbers numbers away.
Tej_csv = "D:/GullyGeoChallenge/data/Results.gdb/Tej_26_28.csv" 
arcpy.ExportXYv_stats(Values_Extracted_to_Points, "RASTERVALU;Distance", "COMMA", Tej_csv, "true")

print "Done"
########## END OF SCRIPT ##########
